apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sk085-ingress-project-tls-cert
  namespace: skala-practice
spec:
  secretName: sk085-ingress-project-tls-cert
  dnsNames:
    - sk085-ingress.skala25a.project.skala-ai.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
