apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: sk085-springboot-practice
  namespace: skala-practice
spec:
  ingressClassName: public-nginx
  rules:
  - host: sk085-ingress.skala25a.project.skala-ai.com
    http:
      paths:
      - backend:
          service:
            name: sk085-springboot-practice
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - sk085-ingress.skala25a.project.skala-ai.com
    secretName: sk085-ingress-project-tls-cert
